[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Theme' 'Navigation buttons' 'Custom branding' 'Premium heading' 'Return YouTube Dislike' 'Hide floating microphone button' 'Hide crowdfunding box' 'Hide breaking news shelf' 'Hide Shorts components' 'SponsorBlock' 'Video ads' 'Hide ads' 'Minimized playback' 'Bypass URL redirects' 'Remove tracking query parameter' 'Client spoof'"
exclusive-patches = true

