enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Video ads' 'Hide ads' 'Disable resuming Shorts on startup' 'SponsorBlock' 'Theme' 'Hide Shorts components' 'Hide breaking news shelf' 'Hide album cards' 'Hide floating microphone button' 'Hide crowdfunding box' 'Return YouTube Dislike' 'Navigation buttons' 'Hide cast button' 'Custom branding' 'Bypass URL redirects' 'Open links externally' 'Client spoof' 'Minimized playback' 'GmsCore support' 'Remove tracking query parameter' 'Downloads'"
exclusive-patches = true


