enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
included-patches = "'Remove tracking query parameter' 'Client spoof' 'Open links externally' 'Bypass URL redirects' 'Minimized playback' 'SponsorBlock' 'Theme' 'Disable rolling number animations' 'Hide crowdfunding box' 'Hide Shorts components' 'Hide floating microphone button' 'Hide layout components' 'Hide album cards' 'Hide player buttons' 'Hide autoplay button' 'Navigation buttons' 'Wide searchbar' 'Disable resuming Shorts on startup' 'Disable player popup panels' 'Custom branding' 'Return YouTube Dislike' 'Video ads' 'Hide ads'"
exclusive-patches = true
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
