logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "client-spoof custom-branding disable-shorts-on-startup external-downloads hdr-auto-brightness hide-shorts-components hide-ads hide-autoplay-button hide-breaking-news-shelf hide-crowdfunding-box hide-watermark minimized-playback open-links-externally premium-heading return-youtube-dislike sponsorblock theme vanced-microg-support video-ads"
exclusive-patches = true